### ISSUE TITLE
Symbol not found: ____chkstk_darwin on MacOS 10.13.6

### ISSUE THREAD

**Issue by Tuxicoman2** [pymupdf/PyMuPDF-wheels#5]
Hi,

The build seems to tells it is compatible with MacOS 10.13 but I have this issue:

```
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fitz/__init__.py", line 10, in <module>
    from fitz.fitz import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fitz/fitz.py", line 15, in <module>
    from . import _fitz
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fitz/_fitz.cpython-39-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fitz/_fitz.cpython-39-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fitz/_fitz.cpython-39-darwin.so
```

**Comment by JorjMcKie** [comment]
I have no Mac OSX machine, so just tested installation and a few basic functions on github.
Everything works fine there: [here](https://github.com/JorjMcKie/py-mupdf/runs/4901795051?check_suite_focus=true) is the run log. This runs on v11.
Have you made sure to upgrade pip to the latest version before installing PyMuPDF?

**Comment by Tuxicoman2** [comment]
Yes, I upgraded pip.
Maybe something related to that : https://github.com/huggingface/tokenizers/issues/321#issuecomment-660147392 ?

I installed brew, mupdf, then pymupdf without the binaries and it works. So it can compile and run for it from my experience.
