### ISSUE TITLE
manually compile wheel

### ISSUE THREAD

**Issue by luhuaei** [pymupdf/PyMuPDF-wheels#6]
Hi, I need to manually generate the pre-version wheel, but  I found the https://github.com/pymupdf/PyMuPDF latest [commit](c5d7bad674d8728caed86387f76bef38a6c800c4) generate wheel not same with wheelhouse wheels.

**Comment by JorjMcKie** [comment]
No, of course this won't work. The repo https://github.com/pymupdf/PyMuPDF only contains the current official version.
My personal staging repo https://github.com/JorjMcKie/py-mupdf contains the stuff from which the pre-wheels are made from.
It only contains the files after SWIG has been executed - so no `*.i` files.
Anyway, this repo is used as a basis for the GitHub actions making the wheels.

**Comment by luhuaei** [comment]
> No, of course this won't work. The repo https://github.com/pymupdf/PyMuPDF only contains the current official version. My personal staging repo https://github.com/JorjMcKie/py-mupdf contains the stuff from which the pre-wheels are made from. It only contains the files after SWIG has been executed - so no `*.i` files. Anyway, this repo is used as a basis for the GitHub actions making the wheels.

Thank you explain and quickly response!!
