### ISSUE TITLE
could you share pymupdf-wheels for windows

### ISSUE THREAD

**Issue by jonewei** [pymupdf/PyMuPDF-wheels#7]
Hello, first of all, thank you for providing Pymupdf for MAC and Linux. Can you provide the Windows version again? thanks a lot!

**Comment by JorjMcKie** [comment]
Sorry to disappoint you, but I cannot do that:
MAC and Linux are generated by Github Actions and copied over to the wheels repo via another Github Action.
The important thing here: **no network costs for me.**

In contrast to this, I am generating all Windows wheels on my local machine. As I am maintaining all of the current Python versions (currently 3.7 through 3.10, and soon also 3.11) in 32-bit and 64-bit, this means 8 (or 10) wheels corresponding to 46 (or 58) megabytes.
As I am connected to the internet via mobile phone (hence pay per volume), the network costs of uploading all these Windows pre-version wheels every now and then would be quite a hit on my pocket. I am paying for PyPI release uploads anyway.

So please ask for a specific Windows pre-version wheel and I will gladly upload it.

**Comment by jonewei** [comment]
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pymupdf/PyMuPDF-wheels"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月30日(星期六) 下午4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pymupdf/PyMuPDF-wheels] could you share pymupdf-wheels for windows (Issue #7)





 
Sorry to disappoint you, but I cannot do that:
 MAC and Linux are generated by Github Actions and copied over to the wheels repo via another Github Action.
 The important thing here: no network costs for me.
 
In contrast to this, I am generating all Windows wheels on my local machine. As I am maintaining all of the current Python versions (currently 3.7 through 3.10, and soon also 3.11) in 32-bit and 64-bit, this means 8 (or 10) wheels corresponding to 46 (or 58) megabytes.
 As I am connected to the internet via mobile phone (hence pay per volume), the network costs of uploading all these Windows pre-version wheels every now and then would be quite a hit on my pocket. I am paying for PyPI release uploads anyway.
 
So please ask for a specific Windows pre-version wheel and I will gladly upload it.
